version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feb-test"
#s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1smfplmhyyger"
#s3_prefix = "feb-test"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
